apiVersion: v1
kind: Service 
metadata: 
  name: controller-service
  labels: 
    run: controller-service 
spec: 
  type: NodePort
  ports: 
  - port: 6633
    protocol: TCP
  selector: 
    app: controller 